- name: Clone repository
  git:
    repo: 'https://github.com/k-gregory/registry.git'
    dest: /home/registry/project

- name: Build project
  command: npm run build
  args:
    chdir: /home/registry/project/frontend
  become: true
  become_user: registry
