jobs:
  include:
    - stage: Test
      language: java
      services:
        - postgresql
      before_script:
        - psql -c 'create database integration_test;' -U postgres
        - cd backend
      before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      script: ./gradlew check -i
      cache:
        directories:
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
    - stage: Test
      language: node_js
      node_js:
        - "node"
      before_install:
        - cd frontend
    - stage: deploy
      language: node_js
      node_js:
        - "node"
      script: skip
      addons:
        ssh_known_hosts: gregory-k.me
      before_deploy:
      - openssl aes-256-cbc -K $encrypted_70c7e4b72870_key -iv $encrypted_70c7e4b72870_iv
        -in ansible_key.enc -out /tmp/ansible_key -d
      - eval "$(ssh-agent -s)"
      - chmod 600 /tmp/ansible_key
      - ssh-add /tmp/ansible_key
      - cd frontend
      - npm install
      - npm run build
      - cd ..
      deploy:
        provider: script
        skip_cleanup: true
        script:
          scp -r frontend/dist ansible-deployer@gregory-k.me:/home/ansible-deployer &&
          ssh ansible-deployer@gregory-k.me 'sudo ansible-pull --vault-id db@/etc/db_keyfile.txt -U https\://github.com/k-gregory/registry ansible/travis-deploy.yml'
        on:
          branch: master
