- name: Install PostgreSQL
  apt: name={{ item }} state=present
  with_items:
    - postgresql-9.5
    - python-psycopg2

- name: Create database user for registry
  postgresql_user:
    name: registry
    state: present
    password: "{{ db_password }}"
  become: true
  become_user: postgres

- name: Create database for registry
  postgresql_db:
    name: registry-db
    encoding: UTF-8
    owner: registry
  become: true
  become_user: postgres  

- name: Enable PostgreSQL service
  systemd:
    name: postgresql
    state: started
    enabled: yes
