spring.jpa.open-in-view: false
spring.jpa.hibernate.ddl-auto: validate

---
spring:
  profiles: gregory-development

spring.datasource.url: jdbc:h2:tcp://localhost/~/Documents/dev-registry
spring.datasource.username: sa

---
#Run with environment variable SPRING_PROFILES_ACTIVE set to kostya-development
spring:
  profiles: kostya-development

spring.datasource.url: jdbc:you-shall-configure-this