- name: Copy SSL certificates
  copy:
    src: "cert/{{ item }}"
    dest: "/etc/ssl/{{ item }}"
    owner: root
    group: root
    mode: 0700
  with_items: [gregory-k.me.crt, gregory-k.me.key]

- name: Install nginx
  apt: name=nginx state=present

- name: Disable default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Copy nginx configuration
  copy: src={{ item }} dest=/etc/nginx/{{ item }}
  notify: Restart nginx
  with_items:
    - sites-available/registry
    - json_errors

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/registry
    dest: /etc/nginx/sites-enabled/registry
    state: link
  notify: Restart nginx  

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
