- name: Install JDK
  apt: name=openjdk-8-jdk state=present

- name: Create user for running backend
  user:
    name: registry
    state: present
    home: /home/registry
    
- name: Copy systemd service file
  template: src=registry.service.j2 dest=/etc/systemd/system/registry.service

- name: Copy application wrapper
  copy:
    src: start-server.sh
    dest: /home/registry
    mode: 0500
    owner: registry
    group: registry

- name: Get git repository
  git:
    repo: 'https://github.com/k-gregory/registry.git'
    dest: /home/registry/project

- name: Build project
  command: ./gradlew build
  args:
    chdir: /home/registry/project/backend
  notify: Restart registry

- name: Determine output file
  shell: ls /home/registry/project/backend/build/libs/registry-*.jar
  register: jar_files

- name: Make link to the built project
  file:
    src: "{{ item }}"
    dest: /home/registry/server.jar
    state: link
  with_items: "{{ jar_files.stdout_lines }}"

- name: Start registry service
  systemd:
    name: registry
    state: started
    enabled: yes
