spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
server.address: 127.0.0.1
---
spring.profiles: gregory-perftest
spring:
  flyway:
    locations: classpath:db/migration/postgresql
  datasource:
    url: jdbc:postgresql:gregory
    username: gregory
  devtools:
    livereload.enabled: false
    restart.enabled: false
---
spring.profiles: production
spring:
  datasource:
    url: jdbc:postgresql:registry-db
    username: registry
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:db/migration/postgresql
swagger:
  host: gregory-k.me
---
spring.profiles: development
spring:
  thymeleaf.cache: false
  flyway.locations: classpath:db/migration/postgresql
logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
swagger:
  host: localhost:8080
---
spring.profiles: gregory-development
spring.profiles.include: development
spring.datasource:
  url: jdbc:postgresql:gregory
  username: gregory
---
spring.profiles: kostya-development
spring.profiles.include: development
spring:
  datasource:
    url: jdbc:postgresql://localhost/registry
    username: postgres
    password: root
---
spring.profiles: integration-test
spring:
  jpa.hibernate.ddl-auto: update
  flyway.locations: classpath:db/migration/h2
logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE