spring.jpa.open-in-view: false
spring.jpa.hibernate.ddl-auto: validate
server.address: 127.0.0.1

---
spring:
  profiles: production

#Set migrations for PostgreSQL
spring.flyway.locations: classpath:db/migration/postgresql

#Configure PostgreSQL datasource
spring.datasource:
  url: jdbc:postgresql:registry-db
  password: ${DB_PASSWORD}

spring.datasource.use
---
spring:
  profiles: development

#Allow reloading templates without application restart
spring.thymeleaf.cache: false

#Pring Hibernate SQL stuff
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#Set migrations for h2
spring.flyway.locations: classpath:db/migration/h2
---
spring:
  profiles: gregory-development
spring.profiles.include: development

spring.datasource.url: jdbc:h2:tcp://localhost/~/Documents/dev-registry
spring.datasource.username: sa

---
#Run with environment variable SPRING_PROFILES_ACTIVE set to kostya-development
spring:
  profiles: kostya-development
spring.profiles.include: development

spring.datasource.url: jdbc:you-shall-configure-this